### ISSUE TITLE
how to add,edit,or delete annotation?

### ISSUE THREAD

**Issue by ruguowoshiyu** [ajedgley/ReBound#1]
I clone the code, download nuscenes dataset, and use your conversion script to change data format. then run code and  point cloud, img and boxes can be displayed normally. however I can't edit annotation, because can't  select a box by clicking.
in your paper, it say:  
   To edit a box’s properties, users must first click
on a desired cuboid in the point cloud window. This will
highlight the bounding box and display the position, rotation, size and annotation class of the selected box in the
control window. 
what can I do to edit/delete a box? 
thanks a lot! I am looking forward to your reply.

**Comment by ajedgley** [comment]
When you open up a dataset, go to the menubar at the top of the screen and select:

Tools > Add/Edit Annotations

From there you will be able to select and edit bounding boxes. In order to select a box in the current scene, you must hold CTRL + Left Click. If the program has difficulties selecting the correct box, simply use the mouse wheel to zoom close to the box you would like to select and try again.

Please let me know if you have any further issues!

**Comment by ruguowoshiyu** [comment]
> When you open up a dataset, go to the menubar at the top of the screen and select:
> 
> Tools > Add/Edit Annotations
> 
> From there you will be able to select and edit bounding boxes. In order to select a box in the current scene, you must hold CTRL + Left Click. If the program has difficulties selecting the correct box, simply use the mouse wheel to zoom close to the box you would like to select and try again.
> 
> Please let me know if you have any further issues!

thanks a lot. hold CTRL + Left Click, I can select a box.but, have a new problem, how to change the size of 3d box? I can't drag the selected box.

**Comment by ajedgley** [comment]
Current mouse operations for our program are limited to:
1. Clicking to select a box (using CTRL + Left Click)
2. Dragging a box around a scene (using Shift + Left Click)

In order to resize a box in scene:
1. Select a box in scene with Ctrl + Left Click
2. Go to the properties window which should now be displaying information about the bounding box
3. Modify the scale values under the Scale section

Under our current implementation, dragging the corners of a box to change it's size is not supported however it is on a list of features that will be added in later updates!
